// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frrdfgdslfjaiiyswzct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZycmRmZ2RzbGZqYWlpeXN3emN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMjcxNTYsImV4cCI6MjA1NTYwMzE1Nn0.Y3H2iq0CWMI0sLgsJFtG-0KYcEw_75D0Uqc9Vrud3yQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);